#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.
# 林博仁(Buo-ren, Lin) © 2019

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

init(){

    exec "${@}"
}

init "${@}"
