#!/usr/bin/env bash
# This launcher sets up ssh-agent, for preserving user entered ssh passphrase credentials
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
	# Ship AddKeysToAgent ssh config if not specified
	mkdir --parent "${HOME}"/.ssh
	if ! grep --no-messages --quiet AddKeysToAgent "${HOME}"/.ssh/config; then
		printf -- '\n%s\n' 'AddKeysToAgent yes' >>"${HOME}"/.ssh/config
	fi

	exec ssh-agent "${@}"
}

init "${@}"
