#!/usr/bin/env bash
# Launcher to fix Git in snap packages
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
	# /etc/gitconfig is not accessible
	GIT_CONFIG_NOSYSTEM=true

	GIT_EXEC_PATH=$SNAP/usr/lib/git-core
	GIT_TEXTDOMAINDIR=$SNAP/usr/share/locale
	GIT_TEMPLATE_DIR=$SNAP/usr/share/git-core/templates

	export \
		GIT_CONFIG_NOSYSTEM \
		GIT_EXEC_PATH \
		GIT_TEXTDOMAINDIR \
		GIT_TEMPLATE_DIR

	exec "${@}"
}

init "${@}"
