#!/usr/bin/env bash
# Launcher to fix Git in snap packages
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
	# /etc/gitconfig is not accessible
	GIT_CONFIG_NOSYSTEM=true

	GIT_EXEC_PATH=$SNAP/usr/lib/git-core
	GIT_TEXTDOMAINDIR=$SNAP/usr/share/locale

	export \
		GIT_CONFIG_NOSYSTEM \
		GIT_EXEC_PATH \
		GIT_TEXTDOMAINDIR

	exec "${@}"
}

init "${@}"

## This script is based on the GNU Bash Shell Script Template project
## https://github.com/Lin-Buo-Ren/GNU-Bash-Shell-Script-Template
## and is based on the following version:
## GNU_BASH_SHELL_SCRIPT_TEMPLATE_VERSION="v3.3.0"
## You may rebase your script to incorporate new features and fixes from the template
