#!/usr/bin/env bash
# Launcher to ship Snappy-specific configurations
# 林博仁 © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
    # Use host GUI editor
    if [ -z "$(git config --global gui.editor)" ]; then
        printf -- \
            'git-cola-launch: Shipping first-time configuration...\n' \
            1>&2
        git config \
            --global \
            gui.editor \
            xdg-open
    fi

    exec "${@}"
}

init "${@}"

## This script is based on the GNU Bash Shell Script Template project
## https://github.com/Lin-Buo-Ren/GNU-Bash-Shell-Script-Template
## and is based on the following version:
## GNU_BASH_SHELL_SCRIPT_TEMPLATE_VERSION="v3.3.0"
## You may rebase your script to incorporate new features and fixes from the template
