#!/usr/bin/env bash
# This launcher setups Tcl/Tk application in snaps.
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
	# tclvars manual page - Tcl Built-In Commands
	# https://www.tcl.tk/man/tcl/TclCmd/tclvars.htm#M7
	TCL_LIBRARY="$SNAP"/usr/share/tcltk/tcl8.6
	
	export TCL_LIBRARY

	exec "${@}"
}

init "${@}"
