#!/usr/bin/env bash
# This launcher setups Tcl/Tk application in snaps.
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
	case "${SNAP_ARCH}" in
		amd64)
			arch_triplet=x86_64-linux-gnu
		;;
		armhf)
			arch_triplet=arm-linux-gnueabihf
		;;
		arm64)
			arch_triplet=aarch64-linux-gnu
		;;
		*)
			arch_triplet="${SNAP_ARCH}"-linux-gnu
		;;
	esac

	# tclvars manual page - Tcl Built-In Commands
	# https://www.tcl.tk/man/tcl/TclCmd/tclvars.htm#M7
	TCL_LIBRARY="$SNAP"/usr/share/tcltk/tcl8.6

	# package manual page - Tcl Built-In Commands
	# https://www.tcl.tk/man/tcl/TclCmd/package.htm
	# DOC: +=: Bash Manual - Basic Shell Features - Shell Parameters
	# DOC: Tcl Improvement Proposals: TIP 407: The String Representation of Tcl Lists: the Gory Details
	# https://core.tcl.tk/tips/doc/trunk/tip/407.md
	TCLLIBPATH="$SNAP/usr/share/tcltk/tcl8.6"
	TCLLIBPATH+=" $SNAP/usr/lib/$arch_triplet"

	export \
		TCL_LIBRARY \
		TCLLIBPATH

	exec "${@}"
}

init "${@}"
