#!/usr/bin/env bash
# This launcher setups Tcl/Tk application in snaps.
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

init(){
	TCL_LIBRARY=$SNAP/usr/share/tcltk/tcl8.6
	
	export TCL_LIBRARY

	exec "${@}"
}

init "${@}"

## This script is based on the GNU Bash Shell Script Template project
## https://github.com/Lin-Buo-Ren/GNU-Bash-Shell-Script-Template
## and is based on the following version:
## GNU_BASH_SHELL_SCRIPT_TEMPLATE_VERSION="v3.3.0"
## You may rebase your script to incorporate new features and fixes from the template
